import { COLORS } from './palette.ts';
import type { EnemyDef, EnemyId } from './types.ts';

/**
 * Shape language: pointed = fast/aggressive, round = swarm, big and angular = tough.
 * Colour = attack type (red contact, magenta ranged, orange explodes, amber summons).
 */
const LIST: EnemyDef[] = [
  {
    id: 'punkt',
    name: 'Punkt',
    desc: 'Schwarm-Futter. Kommt direkt auf dich zu.',
    shape: 'circle',
    color: COLORS.contact,
    radius: 7,
    hp: 6,
    speed: 75,
    damage: 5,
    xp: 1,
    shells: 1,
    knockbackResist: 0,
    ai: { kind: 'chase' },
  },
  {
    id: 'keil',
    name: 'Keil',
    desc: 'Blinkt auf, zieht eine Linie – und sprintet los.',
    shape: 'triangle',
    color: 0xff5a36,
    radius: 10,
    hp: 12,
    speed: 85,
    damage: 8,
    xp: 2,
    shells: 1,
    knockbackResist: 0.1,
    ai: { kind: 'dash', range: 230, windup: 0.5, dashTime: 0.6, dashMult: 3, recover: 0.6 },
  },
  {
    id: 'block',
    name: 'Block',
    desc: 'Langsam, zäh, lässt sich kaum wegstoßen.',
    shape: 'square',
    color: 0xc8243f,
    radius: 14,
    hp: 45,
    speed: 50,
    damage: 9,
    xp: 5,
    shells: 2,
    knockbackResist: 0.7,
    ai: { kind: 'chase' },
  },
  {
    id: 'rhombus',
    name: 'Rhombus',
    desc: 'Kreist um dich und stürzt sich plötzlich hinein.',
    shape: 'diamond',
    color: 0xff6fa8,
    radius: 10,
    hp: 16,
    speed: 120,
    damage: 8,
    xp: 3,
    shells: 1,
    knockbackResist: 0.2,
    ai: {
      kind: 'orbitDive',
      orbitRadius: 200,
      interval: 3,
      windup: 0.35,
      diveTime: 0.75,
      diveMult: 2.2,
    },
  },
  {
    id: 'werfer',
    name: 'Werfer',
    desc: 'Hält Abstand und feuert Kugelringe.',
    shape: 'pentagon',
    color: COLORS.ranged,
    radius: 13,
    hp: 28,
    speed: 65,
    damage: 6,
    xp: 5,
    shells: 1,
    knockbackResist: 0.3,
    ai: {
      kind: 'kite',
      min: 220,
      max: 300,
      interval: 3.5,
      windup: 0.35,
      bullets: 5,
      bulletSpeed: 150,
      bulletDamage: 6,
    },
  },
  {
    id: 'wabe',
    name: 'Wabe',
    desc: 'Ein zäher Bienenstock, der Punkte ausspuckt.',
    shape: 'hexagon',
    color: COLORS.summoner,
    radius: 18,
    hp: 110,
    speed: 35,
    damage: 10,
    xp: 12,
    shells: 3,
    knockbackResist: 0.8,
    ai: { kind: 'spawner', interval: 6, count: 3, spawn: 'punkt' },
  },
  {
    id: 'stern',
    name: 'Stern',
    desc: 'Zündet in deiner Nähe und explodiert – auch für seinesgleichen.',
    shape: 'star5',
    color: COLORS.explosive,
    radius: 12,
    hp: 14,
    speed: 105,
    damage: 25,
    xp: 3,
    shells: 1,
    knockbackResist: 0.1,
    ai: { kind: 'kamikaze', trigger: 110, fuse: 0.8, radius: 80, damage: 25 },
  },
  {
    id: 'sierpinski',
    name: 'Sierpinski',
    desc: 'Teilt sich, statt zu sterben. Teile und herrsche.',
    shape: 'triangle',
    color: COLORS.boss,
    radius: 150,
    hp: 1000,
    speed: 38,
    damage: 20,
    xp: 400,
    shells: 1,
    knockbackResist: 1,
    ai: { kind: 'boss' },
  },
];

export const ENEMIES: Readonly<Record<EnemyId, EnemyDef>> = Object.fromEntries(
  LIST.map((e) => [e.id, e]),
) as Record<EnemyId, EnemyDef>;

export const ENEMY_LIST: readonly EnemyDef[] = LIST;
