import type { MetaUpgradeDef, ProofDef } from './types.ts';

/** "Reißbrett": permanent upgrades bought with Splitter. Cost of the next rank = baseCost × (rank + 1). */
export const META_UPGRADES: readonly MetaUpgradeDef[] = [
  {
    id: 'potenz',
    name: 'Potenz',
    desc: '+5 % Schaden',
    stat: 'might',
    perRank: 0.05,
    maxRank: 5,
    baseCost: 60,
    icon: 'caret',
  },
  {
    id: 'dichte',
    name: 'Dichte',
    desc: '+1 Rüstung',
    stat: 'armor',
    perRank: 1,
    maxRank: 3,
    baseCost: 120,
    icon: 'square',
  },
  {
    id: 'volumen',
    name: 'Volumen',
    desc: '+10 Max-HP',
    stat: 'maxHp',
    perRank: 10,
    maxRank: 5,
    baseCost: 80,
    icon: 'sphere',
  },
  {
    id: 'integral',
    name: 'Integral',
    desc: '+0,1 HP/s',
    stat: 'regen',
    perRank: 0.1,
    maxRank: 5,
    baseCost: 100,
    icon: 'integral',
  },
  {
    id: 'frequenz',
    name: 'Frequenz',
    desc: '−2,5 % Abklingzeit',
    stat: 'cooldown',
    perRank: -0.025,
    maxRank: 2,
    baseCost: 250,
    icon: 'clock',
  },
  {
    id: 'skalierung',
    name: 'Skalierung',
    desc: '+5 % Fläche',
    stat: 'area',
    perRank: 0.05,
    maxRank: 2,
    baseCost: 180,
    icon: 'nested',
  },
  {
    id: 'impuls',
    name: 'Impuls',
    desc: '+10 % Projektiltempo',
    stat: 'projSpeed',
    perRank: 0.1,
    maxRank: 2,
    baseCost: 100,
    icon: 'dart',
  },
  {
    id: 'beschleunigung',
    name: 'Beschleunigung',
    desc: '+5 % Lauftempo',
    stat: 'moveSpeed',
    perRank: 0.05,
    maxRank: 2,
    baseCost: 120,
    icon: 'chevrons',
  },
  {
    id: 'gravitation',
    name: 'Gravitation',
    desc: '+25 % Sammelradius',
    stat: 'magnet',
    perRank: 0.25,
    maxRank: 2,
    baseCost: 80,
    icon: 'inward',
  },
  {
    id: 'wahrscheinlichkeit',
    // Soft hyphen: the longest name breaks as Wahrschein-lichkeit on narrow tiles.
    name: 'Wahrschein­lichkeit',
    desc: '+10 % Glück',
    stat: 'luck',
    perRank: 0.1,
    maxRank: 3,
    baseCost: 150,
    icon: 'diamond',
  },
  {
    id: 'exponent',
    name: 'Exponent',
    desc: '+3 % Erfahrung',
    stat: 'growth',
    perRank: 0.03,
    maxRank: 5,
    baseCost: 100,
    icon: 'gem',
  },
  {
    id: 'gier',
    name: 'Gier',
    desc: '+10 % Splitter',
    stat: 'greed',
    perRank: 0.1,
    maxRank: 5,
    baseCost: 80,
    icon: 'splitter',
  },
  {
    id: 'neuzeichnen',
    name: 'Neu zeichnen',
    desc: '+1 Reroll pro Run',
    stat: 'reroll',
    perRank: 1,
    maxRank: 3,
    baseCost: 200,
    icon: 'sigma',
  },
  {
    id: 'radieren',
    name: 'Radieren',
    desc: '+1 Radieren pro Run',
    stat: 'banish',
    perRank: 1,
    maxRank: 3,
    baseCost: 200,
    icon: 'times',
  },
  {
    id: 'ueberspringen',
    name: 'Überspringen',
    desc: '+1 Überspringen pro Run',
    stat: 'skip',
    perRank: 1,
    maxRank: 3,
    baseCost: 100,
    icon: 'divide',
  },
  {
    id: 'zweiterversuch',
    name: 'Zweiter Versuch',
    desc: 'Einmal pro Run wiederbeleben',
    stat: 'revival',
    perRank: 1,
    maxRank: 1,
    baseCost: 800,
    icon: 'pentagon',
  },
  {
    id: 'viertekarte',
    name: 'Vierte Karte',
    desc: '4 statt 3 Karten beim Level-Up',
    stat: 'draftSize',
    perRank: 1,
    maxRank: 1,
    baseCost: 1000,
    icon: 'cube',
  },
];

/** "Beweise": achievements that add content to the pools. */
export const PROOFS: readonly ProofDef[] = [
  {
    id: 'ersterBeweis',
    name: 'Erster Beweis',
    desc: 'Überlebe 5:00 Minuten.',
    condition: { kind: 'surviveSeconds', value: 300 },
    unlocks: ['weapon:strahl'],
  },
  {
    id: 'quadratur',
    name: 'Quadratur',
    desc: 'Erreiche die Form Quadrat.',
    condition: { kind: 'reachVertices', value: 4 },
    unlocks: ['axiom:symmetrie'],
  },
  {
    id: 'vollendeteForm',
    name: 'Vollendete Form',
    desc: 'Erreiche die Form Hexagon.',
    condition: { kind: 'reachVertices', value: 6 },
    unlocks: ['char:nova'],
  },
  {
    id: 'qed',
    name: 'Q.E.D.',
    desc: 'Beweise dein erstes Theorem.',
    condition: { kind: 'theorems', value: 1 },
    unlocks: ['weapon:fraktal'],
  },
  {
    id: 'tausendPunkte',
    name: 'Tausend Punkte',
    desc: 'Besiege 1000 Gegner in einem Run.',
    condition: { kind: 'killsInRun', value: 1000 },
    unlocks: ['axiom:integral'],
  },
  {
    id: 'teileUndHerrsche',
    name: 'Teile und herrsche',
    desc: 'Besiege Sierpinski.',
    condition: { kind: 'bossKilled' },
    unlocks: ['mode:endless'],
  },
];
