import type { MetaUpgradeDef, ProofDef } from './types.ts';

/**
 * "Reißbrett": permanent upgrades bought with Splitter. `ranks` is the max rank without
 * Erweiterung and with Erweiterung I, II and III; prices see `META` in tuning.ts.
 */
export const META_UPGRADES: readonly MetaUpgradeDef[] = [
  {
    id: 'potenz',
    name: 'Potenz',
    desc: '+5 % Schaden',
    stat: 'might',
    perRank: 0.05,
    ranks: [5, 10, 15, 20],
    baseCost: 60,
    icon: 'caret',
    locked: false,
  },
  {
    id: 'dichte',
    name: 'Dichte',
    desc: '+1 Rüstung',
    stat: 'armor',
    perRank: 1,
    ranks: [3, 4, 5, 6],
    baseCost: 120,
    icon: 'square',
    locked: false,
  },
  {
    id: 'volumen',
    name: 'Volumen',
    desc: '+10 Max-HP',
    stat: 'maxHp',
    perRank: 10,
    ranks: [5, 10, 15, 20],
    baseCost: 80,
    icon: 'sphere',
    locked: false,
  },
  {
    id: 'integral',
    name: 'Integral',
    desc: '+0,1 HP/s',
    stat: 'regen',
    perRank: 0.1,
    ranks: [5, 10, 15, 20],
    baseCost: 100,
    icon: 'integral',
    locked: false,
  },
  {
    id: 'frequenz',
    name: 'Frequenz',
    desc: '−2,5 % Abklingzeit',
    stat: 'cooldown',
    perRank: -0.025,
    ranks: [2, 4, 6, 8],
    baseCost: 250,
    icon: 'clock',
    locked: false,
  },
  {
    id: 'skalierung',
    name: 'Skalierung',
    desc: '+5 % Fläche',
    stat: 'area',
    perRank: 0.05,
    ranks: [2, 4, 6, 8],
    baseCost: 180,
    icon: 'nested',
    locked: false,
  },
  {
    id: 'impuls',
    name: 'Impuls',
    desc: '+10 % Projektiltempo',
    stat: 'projSpeed',
    perRank: 0.1,
    ranks: [2, 3, 4, 5],
    baseCost: 100,
    icon: 'dart',
    locked: false,
  },
  {
    id: 'beschleunigung',
    name: 'Beschleunigung',
    desc: '+5 % Lauftempo',
    stat: 'moveSpeed',
    perRank: 0.05,
    ranks: [2, 3, 4, 6],
    baseCost: 120,
    icon: 'chevrons',
    locked: false,
  },
  {
    id: 'gravitation',
    name: 'Gravitation',
    desc: '+25 % Sammelradius',
    stat: 'magnet',
    perRank: 0.25,
    ranks: [2, 3, 4, 6],
    baseCost: 80,
    icon: 'inward',
    locked: false,
  },
  {
    id: 'wahrscheinlichkeit',
    // Soft hyphen: the longest name breaks as Wahrschein-lichkeit on narrow tiles.
    name: 'Wahrschein­lichkeit',
    desc: '+10 % Glück',
    stat: 'luck',
    perRank: 0.1,
    ranks: [3, 5, 8, 10],
    baseCost: 150,
    icon: 'diamond',
    locked: false,
  },
  {
    id: 'exponent',
    name: 'Exponent',
    desc: '+3 % Erfahrung',
    stat: 'growth',
    perRank: 0.03,
    ranks: [5, 10, 15, 20],
    baseCost: 100,
    icon: 'gem',
    locked: false,
  },
  {
    id: 'gier',
    name: 'Gier',
    desc: '+10 % Splitter',
    stat: 'greed',
    perRank: 0.1,
    ranks: [5, 8, 10, 12],
    baseCost: 80,
    icon: 'splitter',
    locked: false,
  },
  {
    id: 'neuzeichnen',
    name: 'Neu zeichnen',
    desc: '+1 Reroll pro Run',
    stat: 'reroll',
    perRank: 1,
    ranks: [3, 5, 7, 10],
    baseCost: 200,
    icon: 'sigma',
    locked: false,
  },
  {
    id: 'radieren',
    name: 'Radieren',
    desc: '+1 Radieren pro Run',
    stat: 'banish',
    perRank: 1,
    ranks: [3, 4, 5, 6],
    baseCost: 200,
    icon: 'times',
    locked: false,
  },
  {
    id: 'ueberspringen',
    name: 'Überspringen',
    desc: '+1 Überspringen pro Run',
    stat: 'skip',
    perRank: 1,
    ranks: [3, 4, 5, 6],
    baseCost: 100,
    icon: 'divide',
    locked: false,
  },
  {
    id: 'zweiterversuch',
    name: 'Zweiter Versuch',
    desc: '+1 Wiederbelebung pro Run',
    stat: 'revival',
    perRank: 1,
    ranks: [1, 1, 2, 3],
    baseCost: 800,
    icon: 'pentagon',
    locked: false,
  },
  {
    id: 'viertekarte',
    name: 'Vierte Karte',
    desc: '4 statt 3 Karten beim Level-Up',
    stat: 'draftSize',
    perRank: 1,
    ranks: [1, 1, 1, 1],
    baseCost: 1000,
    icon: 'cube',
    locked: false,
  },
  {
    id: 'tangente',
    name: 'Tangente',
    desc: '+2 % Krit-Chance',
    stat: 'crit',
    perRank: 0.02,
    ranks: [3, 5, 8, 10],
    baseCost: 150,
    icon: 'tangent',
    locked: true,
  },
  {
    id: 'extremum',
    name: 'Extremum',
    desc: '+10 % Krit-Schaden',
    stat: 'critMult',
    perRank: 0.1,
    ranks: [3, 5, 8, 10],
    baseCost: 150,
    icon: 'extremum',
    locked: true,
  },
  {
    id: 'kontinuitaet',
    name: 'Kontinuität',
    desc: '+5 % Wirkdauer',
    stat: 'duration',
    perRank: 0.05,
    ranks: [2, 3, 5, 6],
    baseCost: 150,
    icon: 'infinity',
    locked: true,
  },
  {
    id: 'kombinatorik',
    name: 'Kombinatorik',
    desc: '+1 Upgrade pro Würfel',
    stat: 'cubeRolls',
    perRank: 1,
    ranks: [1, 2, 2, 3],
    baseCost: 500,
    icon: 'dice',
    locked: true,
  },
  {
    id: 'induktion',
    name: 'Induktion',
    desc: 'Startwaffe +1 Level',
    stat: 'startLevel',
    perRank: 1,
    ranks: [1, 2, 3, 4],
    baseCost: 300,
    icon: 'stairs',
    locked: true,
  },
  {
    id: 'vielfaches',
    name: 'Vielfaches',
    desc: '+1 Projektil, Kreis oder Strahl',
    stat: 'amount',
    perRank: 1,
    ranks: [1, 1, 1, 2],
    baseCost: 4000,
    icon: 'mirror',
    locked: true,
  },
];

/** "Beweise": achievements that add content to the pools. */
export const PROOFS: readonly ProofDef[] = [
  {
    id: 'ersterBeweis',
    name: 'Erster Beweis',
    desc: 'Überlebe 5:00 Minuten.',
    condition: { kind: 'surviveSeconds', value: 300 },
    unlocks: ['weapon:strahl'],
  },
  {
    id: 'quadratur',
    name: 'Quadratur',
    desc: 'Erreiche die Form Quadrat.',
    condition: { kind: 'reachVertices', value: 4 },
    unlocks: ['axiom:symmetrie'],
  },
  {
    id: 'vollendeteForm',
    name: 'Vollendete Form',
    desc: 'Erreiche die Form Hexagon.',
    condition: { kind: 'reachVertices', value: 6 },
    unlocks: ['char:nova'],
  },
  {
    id: 'qed',
    name: 'Q.E.D.',
    desc: 'Beweise dein erstes Theorem.',
    condition: { kind: 'theorems', value: 1 },
    unlocks: ['weapon:fraktal'],
  },
  {
    id: 'tausendPunkte',
    name: 'Tausend Punkte',
    desc: 'Besiege 1000 Gegner in einem Run.',
    condition: { kind: 'killsInRun', value: 1000 },
    unlocks: ['axiom:integral'],
  },
  {
    id: 'teileUndHerrsche',
    name: 'Teile und herrsche',
    desc: 'Besiege Sierpinski.',
    condition: { kind: 'bossKilled' },
    unlocks: ['mode:endless'],
  },
  {
    id: 'fuenftausend',
    name: 'Fünftausend',
    desc: 'Besiege 5000 Gegner in einem Run.',
    condition: { kind: 'killsInRun', value: 5000 },
    unlocks: ['meta:tangente'],
  },
  {
    id: 'ueberstufe',
    name: 'Überstufe',
    desc: 'Bringe eine Waffe auf Level 25.',
    condition: { kind: 'weaponLevel', value: 25 },
    unlocks: ['meta:kombinatorik'],
  },
  {
    id: 'kritischerPunkt',
    name: 'Kritischer Punkt',
    desc: 'Besiege Sierpinski auf Komplexität 5.',
    condition: { kind: 'complexityCleared', value: 5 },
    unlocks: ['meta:kontinuitaet'],
  },
  {
    id: 'wiederkehr',
    name: 'Wiederkehr',
    desc: 'Besiege Sierpinski zweimal in einem Run.',
    condition: { kind: 'bossKillsInRun', value: 2 },
    unlocks: ['meta:extremum'],
  },
  {
    id: 'hundert',
    name: 'Hundert',
    desc: 'Erreiche Level 100 in einem Run.',
    condition: { kind: 'reachLevel', value: 100 },
    unlocks: ['meta:induktion'],
  },
  {
    id: 'grenzwert',
    name: 'Grenzwert',
    desc: 'Überlebe 30:00 Minuten.',
    condition: { kind: 'surviveSeconds', value: 1800 },
    unlocks: ['tier:1'],
  },
  {
    id: 'konvergenz',
    name: 'Konvergenz',
    desc: 'Besiege Sierpinski auf Komplexität 10.',
    condition: { kind: 'complexityCleared', value: 10 },
    unlocks: ['tier:2'],
  },
  {
    id: 'komplexitaetXV',
    name: 'Komplexität XV',
    desc: 'Besiege Sierpinski auf Komplexität 15.',
    condition: { kind: 'complexityCleared', value: 15 },
    unlocks: ['meta:vielfaches'],
  },
  {
    id: 'unendlichkeit',
    name: 'Unendlichkeit',
    desc: 'Überlebe 40:00 Minuten.',
    condition: { kind: 'surviveSeconds', value: 2400 },
    unlocks: ['tier:3'],
  },
  {
    id: 'formvollendet',
    name: 'Formvollendet',
    desc: 'Besiege Sierpinski auf Komplexität 20.',
    condition: { kind: 'complexityCleared', value: 20 },
    unlocks: [],
  },
];
