import type { WeaponDef, WeaponId, WeaponParams } from './types.ts';

/** All-zero params; weapon definitions override only what their kind uses. */
export function params(p: Partial<WeaponParams>): WeaponParams {
  return {
    damage: 0,
    cooldown: 0,
    amount: 0,
    speed: 0,
    pierce: 0,
    area: 1,
    duration: 0,
    hitInterval: 0,
    knockback: 0,
    radius: 0,
    orbitSpeed: 0,
    amplitude: 0,
    wavelength: 0,
    length: 0,
    width: 0,
    depth: 0,
    childFactor: 0,
    slow: 0,
    allVertices: 0,
    moons: 0,
    harmonics: 0,
    pulse: 0,
    prism: 0,
    homing: 0,
    alwaysOn: 0,
    fan: 0,
    heal: 0,
    ...p,
  };
}

const INFINITE_PIERCE = 9999;

const LIST: WeaponDef[] = [
  {
    id: 'spitze',
    name: 'Spitze',
    desc: 'Schießt Dreieckspfeile von ihrer Ecke auf den nächsten Gegner.',
    kind: 'bolt',
    color: 0x3ff0ff,
    icon: 'dart',
    base: params({
      damage: 10,
      cooldown: 1,
      amount: 1,
      speed: 450,
      pierce: 1,
      duration: 1.4,
      knockback: 60,
    }),
    levels: [
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Pfeil' },
      { ops: [{ key: 'damage', add: 5 }], text: '+5 Schaden' },
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Pfeil' },
      { ops: [{ key: 'pierce', add: 1 }], text: '+1 Durchschlag' },
      { ops: [{ key: 'cooldown', mul: 0.85 }], text: '−15 % Abklingzeit' },
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Pfeil' },
      { ops: [{ key: 'damage', add: 10 }], text: '+10 Schaden' },
    ],
    evolvesWith: 'symmetrie',
    evolvesInto: 'sternpolygon',
    locked: false,
  },
  {
    id: 'kreisbahn',
    name: 'Kreisbahn',
    desc: 'Kreise umrunden dich und treffen alles auf ihrer Bahn.',
    kind: 'orbit',
    color: 0x9dffea,
    icon: 'orb',
    base: params({
      damage: 10,
      amount: 2,
      radius: 80,
      orbitSpeed: 3,
      hitInterval: 0.5,
      knockback: 120,
    }),
    levels: [
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Kreis' },
      { ops: [{ key: 'radius', mul: 1.2 }], text: '+20 % Bahnradius' },
      { ops: [{ key: 'damage', add: 5 }], text: '+5 Schaden' },
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Kreis' },
      { ops: [{ key: 'orbitSpeed', mul: 1.25 }], text: '+25 % Umlauftempo' },
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Kreis' },
      { ops: [{ key: 'damage', add: 10 }], text: '+10 Schaden' },
    ],
    evolvesWith: 'gravitation',
    evolvesInto: 'epizykel',
    locked: false,
  },
  {
    id: 'welle',
    name: 'Welle',
    desc: 'Ein Sinus-Geschoss in Blickrichtung, das alles durchdringt.',
    kind: 'wave',
    color: 0x7ad7ff,
    icon: 'sine',
    base: params({
      damage: 12,
      cooldown: 1.5,
      amount: 1,
      speed: 320,
      pierce: INFINITE_PIERCE,
      duration: 1.6,
      amplitude: 40,
      wavelength: 160,
      knockback: 40,
    }),
    levels: [
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Welle (rückwärts)' },
      { ops: [{ key: 'damage', add: 5 }], text: '+5 Schaden' },
      { ops: [{ key: 'amplitude', mul: 1.25 }], text: '+25 % Amplitude' },
      { ops: [{ key: 'cooldown', mul: 0.85 }], text: '−15 % Abklingzeit' },
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Welle' },
      { ops: [{ key: 'damage', add: 10 }], text: '+10 Schaden' },
      { ops: [{ key: 'area', mul: 1.25 }], text: '+25 % Größe' },
    ],
    evolvesWith: 'frequenz',
    evolvesInto: 'fourier',
    locked: false,
  },
  {
    id: 'zirkel',
    name: 'Zirkel',
    desc: 'Ein Schadensring um dich, der Gegner leicht zurückstößt.',
    kind: 'aura',
    color: 0xc9f5ff,
    icon: 'ring',
    base: params({ damage: 6, hitInterval: 0.5, radius: 70, knockback: 30 }),
    levels: [
      { ops: [{ key: 'radius', mul: 1.15 }], text: '+15 % Radius' },
      { ops: [{ key: 'damage', add: 3 }], text: '+3 Schaden' },
      { ops: [{ key: 'hitInterval', mul: 0.8 }], text: '−20 % Tick-Intervall' },
      { ops: [{ key: 'radius', mul: 1.15 }], text: '+15 % Radius' },
      { ops: [{ key: 'damage', add: 4 }], text: '+4 Schaden' },
      { ops: [{ key: 'radius', mul: 1.15 }], text: '+15 % Radius' },
      { ops: [{ key: 'slow', add: 0.25 }], text: 'Verlangsamt Gegner um 25 %' },
    ],
    evolvesWith: 'volumen',
    evolvesInto: 'sphaere',
    locked: false,
  },
  {
    id: 'strahl',
    name: 'Strahl',
    desc: 'Laser radial aus seiner Ecke – fegt mit der Drehung deiner Form.',
    kind: 'beam',
    color: 0xffffff,
    icon: 'edge',
    base: params({
      damage: 5,
      hitInterval: 0.1,
      cooldown: 3,
      duration: 1,
      length: 220,
      width: 8,
      amount: 1,
    }),
    levels: [
      { ops: [{ key: 'length', mul: 1.2 }], text: '+20 % Länge' },
      { ops: [{ key: 'damage', add: 2 }], text: '+2 Schaden' },
      { ops: [{ key: 'duration', add: 0.5 }], text: '+0,5 s Dauer' },
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Strahl (Fächer)' },
      { ops: [{ key: 'cooldown', mul: 0.8 }], text: '−20 % Abklingzeit' },
      { ops: [{ key: 'width', mul: 1.4 }], text: '+40 % Breite' },
      { ops: [{ key: 'damage', add: 3 }], text: '+3 Schaden' },
    ],
    evolvesWith: 'skalierung',
    evolvesInto: 'prisma',
    locked: true,
  },
  {
    id: 'fraktal',
    name: 'Fraktal',
    desc: 'Ein Dreieck, das beim Treffer in drei kleinere zerfällt.',
    kind: 'fractal',
    color: 0xb8ff7a,
    icon: 'fractal',
    base: params({
      damage: 18,
      cooldown: 1.8,
      amount: 1,
      speed: 360,
      pierce: 1,
      depth: 1,
      childFactor: 0.5,
      duration: 2,
      knockback: 80,
    }),
    levels: [
      { ops: [{ key: 'damage', add: 6 }], text: '+6 Schaden' },
      { ops: [{ key: 'depth', add: 1 }], text: '+1 Rekursionstiefe' },
      { ops: [{ key: 'amount', add: 1 }], text: '+1 Fraktal' },
      { ops: [{ key: 'cooldown', mul: 0.85 }], text: '−15 % Abklingzeit' },
      { ops: [{ key: 'depth', add: 1 }], text: '+1 Rekursionstiefe' },
      { ops: [{ key: 'damage', add: 10 }], text: '+10 Schaden' },
      { ops: [{ key: 'childFactor', add: 0.25 }], text: 'Kinder erben 75 % Schaden' },
    ],
    evolvesWith: 'potenz',
    evolvesInto: 'mandelbrot',
    locked: true,
  },

  // ---------------------------------------------------------------- Theoreme (Evolutionen)
  {
    id: 'sternpolygon',
    name: 'Sternpolygon',
    desc: 'Salven aus allen Ecken gleichzeitig. Pfeile durchschlagen mehr.',
    kind: 'bolt',
    color: 0xfff07a,
    icon: 'star5',
    base: params({}),
    levels: [],
    theoremOf: 'spitze',
    theoremOps: [
      { key: 'allVertices', add: 1 },
      { key: 'pierce', add: 2 },
      { key: 'speed', mul: 1.2 },
      { key: 'cooldown', mul: 0.8 },
    ],
    locked: false,
  },
  {
    id: 'epizykel',
    name: 'Epizykel',
    desc: 'Jeder Kreis bekommt zwei eigene Monde – Spirograph-Bahnen.',
    kind: 'orbit',
    color: 0xa0ffd8,
    icon: 'orb',
    base: params({}),
    levels: [],
    theoremOf: 'kreisbahn',
    theoremOps: [
      { key: 'moons', add: 2 },
      { key: 'area', mul: 1.2 },
      { key: 'damage', mul: 1.2 },
    ],
    locked: false,
  },
  {
    id: 'fourier',
    name: 'Fourier-Reihe',
    desc: 'Drei überlagerte Harmonische formen eine Rechteckwelle – im Fächer.',
    kind: 'wave',
    color: 0x9fe8ff,
    icon: 'squarewave',
    base: params({}),
    levels: [],
    theoremOf: 'welle',
    theoremOps: [
      { key: 'harmonics', add: 3 },
      { key: 'fan', add: 1 },
      { key: 'damage', mul: 1.25 },
      { key: 'amplitude', mul: 1.2 },
    ],
    locked: false,
  },
  {
    id: 'sphaere',
    name: 'Sphäre',
    desc: 'Größerer Ring mit Schockwellen-Puls. Kills im Ring heilen dich.',
    kind: 'aura',
    color: 0xe6fbff,
    icon: 'ring',
    base: params({}),
    levels: [],
    theoremOf: 'zirkel',
    theoremOps: [
      { key: 'radius', mul: 1.3 },
      { key: 'pulse', add: 2 },
      { key: 'heal', add: 0.5 },
    ],
    locked: false,
  },
  {
    id: 'prisma',
    name: 'Prisma',
    desc: 'Dauerstrahl, der sich in drei Spektralstrahlen aufspaltet.',
    kind: 'beam',
    color: 0xffffff,
    icon: 'triangle',
    base: params({}),
    levels: [],
    theoremOf: 'strahl',
    theoremOps: [
      { key: 'alwaysOn', add: 1 },
      { key: 'prism', add: 3 },
      { key: 'damage', mul: 0.8 },
      { key: 'length', mul: 1.2 },
    ],
    locked: false,
  },
  {
    id: 'mandelbrot',
    name: 'Mandelbrot',
    desc: 'Rekursionstiefe 4, Kinder suchen ihr Ziel selbst.',
    kind: 'fractal',
    color: 0xd4ff9a,
    icon: 'fractal',
    base: params({}),
    levels: [],
    theoremOf: 'fraktal',
    theoremOps: [
      { key: 'depth', add: 1 },
      { key: 'homing', add: 1 },
      { key: 'damage', mul: 1.2 },
    ],
    locked: false,
  },
];

export const WEAPONS: Readonly<Record<WeaponId, WeaponDef>> = Object.fromEntries(
  LIST.map((w) => [w.id, w]),
) as Record<WeaponId, WeaponDef>;

export const WEAPON_LIST: readonly WeaponDef[] = LIST;
export const BASE_WEAPONS: readonly WeaponDef[] = LIST.filter((w) => w.theoremOf === undefined);
export const THEOREMS: readonly WeaponDef[] = LIST.filter((w) => w.theoremOf !== undefined);
